version: "3"
services:
  # backend:
  #   build: ./backend
  #   container_name: backend-container
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./backend:/app
  #     - /app/node_modules
  #     - /var/run/docker.sock:/var/run/docker.sock  # ✅ Allow backend to run Docker commands
  #   depends_on:
  #     - sandbox-js
  #     - sandbox-python
  #     - sandbox-cpp
  #     - redis

  signaling-server:
    build: ./y-webrtc
    container_name: signaling-server
    restart: always
    ports:
      - "4444:4444"  # Mapping host port 4444 to container's internal 8080
    environment:
      - PORT=4444  # Must match the ENV PORT in Dockerfile

  sandbox-js:
    build: ./sandbox-js
    container_name: sandbox-js
    stdin_open: true
    tty: true

  sandbox-python:
    build: ./sandbox-python
    container_name: sandbox-python
    stdin_open: true
    tty: true

  sandbox-cpp:
    build: ./sandbox-cpp
    container_name: sandbox-cpp
    stdin_open: true
    tty: true

  redis:
    image: redis:latest
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
